guide_michelin_accueil:
  path: /accueil/{nom}
  controller: App\Controller\GuideController::accueil
  defaults:
    nom: "..."

guide_michelin_menu:
  path: /menu/{nom}
  controller: App\Controller\GuideController::menu
  defaults:
    nom: "..."

guide_michelin_ajouter:
  path: /ajouter/{nom}-{chef}-{etoiles}
  controller: App\Controller\GuideController::ajouter

guide_michelin_voir:
  path: /voir/{id}
  controller: App\Controller\GuideController::voir
  requirements:
    numero: \d+

guide_michelin_ajouter_request:
  path: /resto/ajout
  controller: App\Controller\GuideController::ajouterRequest

guide_michelin_list:
  path: /resto/list/{nom}
  controller: App\Controller\GuideController::list
  defaults:
    nom: "..."

guide_michelin_modifier:
  path: /modifier/{id}
  controller: App\Controller\GuideController::modifierResto
  requirements:
    id: \d+

guide_michelin_modifier_soumission:
  path: /modifierSoumission/{id}
  controller: App\Controller\GuideController::modifierSoumission
  methods: POST

guide_michelin_suppression:
  path: /supprimer/{id}
  controller: App\Controller\GuideController::supprimer

guide_michelin_list_etoiles:
  path: /resto/voir/{nb}
  controller: App\Controller\GuideController::findEtoiles
  defaults:
    nb: 1

guide_michelin_list_etoiles_inf:
  path: /resto/voir/inf/{nb}
  controller: App\Controller\GuideController::findEtoilesInf
  defaults:
    nb: 1

guide_michelin_list_etoiles_sup:
  path: /resto/voir/sup/{nb}
  controller: App\Controller\GuideController::findEtoilesSup
  defaults:
    nb: 1

guide_michelin_add_etoiles:
  path: /resto/ajout/etoiles
  controller: App\Controller\GuideController::addEtoiles

guide_michelin_list_chef:
  path: /resto/voir/chef/{chef}
  controller: App\Controller\GuideController::findRestoChef
  defaults:
    chef: ""

guide_michelin_suppression_chef:
  path: /supprimer/chef/{id}
  controller: App\Controller\GuideController::removeChef

