guide_michelin_accueil:
  path: /accueil/{nom}
  controller: App\Controller\GuideController::accueil
  defaults:
    nom: "..."

guide_michelin_menu:
  path: /menu/{nom}
  controller: App\Controller\GuideController::menu
  defaults:
    nom: "..."

guide_michelin_ajouter:
  path: /ajouter/{nom}-{chef}-{etoiles}
  controller: App\Controller\GuideController::ajouter

guide_michelin_voir:
  path: /voir/{id}
  controller: App\Controller\GuideController::voir
  requirements:
    numero: \d+

guide_michelin_ajouter_request:
  path: /resto/ajout
  controller: App\Controller\GuideController::ajouterRequest